version: '3.4'

services:
  apigateway:
    image: apigateway
    build:
        context: .
        dockerfile: ApiGateway/Dockerfile
    ports:
        - "5000:80"
    depends_on:
        - userservice
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    networks:
        - contollo_network

  userservice:
    image: userservice
    build:
        context: .
        dockerfile: UserService/Dockerfile
    ports:
    - "5001:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    networks:
        - contollo_network

networks:
    contollo_network: