version: '3.4'

services:
  apigateway:
    image: apigateway
    build:
        context: .
        dockerfile: ApiGateway/Dockerfile
    ports:
        - "5000:80"
    depends_on:
        - userservice
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    networks:
        - contollo_network

  userservice:
    image: userservice
    build:
        context: .
        dockerfile: UserService/Dockerfile
    ports:
    - "5001:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    networks:
        - contollo_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"
    environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: "123456"

networks:
    contollo_network: